[build]
# Use sccache to cache build artifacts
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
# Use clang as the linker driver
linker = "clang"
# Force use of mold linker
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
